### PR TITLE
Add pre-built config for Fedora.

### PR DESCRIPTION
**Pull request by glima**
This way we get rid of what we don't want from the default
configuration. We also now do our compiling in the %install section only
and don't try to package builtins.json anymore.

### CODE REVIEW

**Comment by glima** [comment]
@dorileo @anselmolsm what do you say?

**Comment by glima** [comment]
There is no such thing as systemd 221 on Fedora yet (only 219). With have to deal with it.

**Comment by glima** [comment]
Just as a heads up, I'm now just waiting this to get in to generate a release and start interacting with rpmfusion.

**Comment by dorileo** [comment]
patchset looks good, just few minor issues, don't even need to respin it, IMO you could just fix the issues on merging time.

**Comment by glima** [comment]
Thanks a lot, merging soon.

**Pull request merged**
